services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
    - "${FRONTEND_PORT:-80}:80"
    # Uncomment below if you need to run it with SSL certificate, and edit frontend/Dockerfile nginx command
    # volumes:
    #   - /etc/letsencrypt:/etc/letsencrypt
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    # Uncomment below if you need to run it with SSL certificate, and edit api/Dockerfile gunicorn command
    # volumes:
    #   - /etc/letsencrypt:/etc/letsencrypt

  worker:
    privileged: true
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    environment:
      - TIME_LIMIT=${TIME_LIMIT:-20}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-user}
      - CELERY_RESULT_EXPIRE=${CELERY_RESULT_EXPIRE:-86400}
    entrypoint: celery
    command: -A tasks worker --loglevel=info
    restart: always
    deploy:
      mode: replicated
      replicas: ${WORKER_NUMBERS:-1}
      resources:
        limits:
          memory: ${MAX_MEMORY_PER_DOCKER_WORKER:-500M}
    depends_on:
      - redis
      - mysql

  monitor:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: celery
    command:  -A tasks --broker=redis://redis:6379/0 flower --port=5555 --basic_auth=${FLOWER_USERNAME:-username}:${FLOWER_PASSWORD:-password} --max_tasks=${FLOWER_MONITOR_MAX_TASKS:-10000}
    depends_on:
      - redis

  redis:
    image: redis

  mysql:
    image: mysql:8.4
    restart: always
    command: --wait_timeout=600 --max_connections=2048
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    ports:
      - '3306:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
    user: ${CURRENT_USER_ID:-1000}:${CURRENT_GROUP_ID:-1000}
