version: "3"
services:
  web:
    privileged: true
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis

  worker:
    privileged: true
    build:
      context: celery-queue
      dockerfile: Dockerfile
    environment:
      - TIME_LIMIT=${TIME_LIMIT:-20}
    entrypoint: celery
    command: -A tasks worker --loglevel=info --max-memory-per-child=${MAX_MEMORY_PER_CHILD:-12000}
    depends_on:
      - redis
    
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0 --basic_auth=${FLOWER_USERNAME:-username}:${FLOWER_PASSWORD:-password}
    depends_on:
      - redis
  redis:
    image: redis
